### ISSUE TITLE
why is there an error if there is `--paths temp:~/yt-dlp_temp` in `yt-dlp.conf`

### ISSUE THREAD

**Issue by candrapersada** [bitingsock/ytdl-preload#6]
> [ytdl_preload] removing faulty video (entry number: 2) from playlist
> [ytdl_preload] WARNING: --paths is ignored since an absolute path is given in output template

**Comment by bitingsock** [comment]
because we call yt-dl with a specified output path.
https://github.com/bitingsock/ytdl-preload/blob/12ac34b4e1082c92d3d7180ca48b6cec79c7fe6c/ytdl-preload.lua#L284
not really an error.

**Comment by candrapersada** [comment]
but `[ytdl_preload] removing faulty video (entry number: 2) from playlist` if `[ytdl_preload] WARNING: --paths is ignored since an absolute path is given in output template`

**Comment by bitingsock** [comment]
those lines are detailing separate issues. first shouldn't have anything to do with the other

**Comment by candrapersada** [comment]
if remove `--paths temp:~/yt-dlp_temp` in `yt-dlp.conf`
there will be no warning `[ytdl_preload] removing faulty video (entry number: 2) from playlist`
but if create `--paths temp:~/yt-dlp_temp` in `yt-dlp.conf`
there will be a warning [ytdl_preload] removing faulty video (entry number: 2) from playlist
https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#configuration
